# Generated by Django 3.2.8 on 2021-10-28 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datacovid', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='datacovid',
            name='daerah',
            field=models.CharField(default='DEFAULT VALUE', max_length=200),
        ),
        migrations.AddField(
            model_name='datacovid',
            name='positif',
            field=models.CharField(default='DEFAULT VALUE', max_length=200),
        ),
    ]
