# Generated by Django 3.2.8 on 2021-10-29 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datacovid', '0002_auto_20211028_1816'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datacovid',
            name='daerah',
            field=models.CharField(max_length=200, verbose_name='Daerah'),
        ),
        migrations.AlterField(
            model_name='datacovid',
            name='positif',
            field=models.CharField(max_length=200, verbose_name='Positif'),
        ),
    ]
