# Generated by Django 3.2.8 on 2021-10-29 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datacovid', '0003_auto_20211029_0757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datacovid',
            name='daerah',
            field=models.CharField(max_length=200, verbose_name='daerah'),
        ),
        migrations.AlterField(
            model_name='datacovid',
            name='positif',
            field=models.CharField(max_length=200, verbose_name='positif'),
        ),
    ]
