# Generated by Django 3.2.7 on 2021-10-30 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kategori',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_kategori', models.CharField(max_length=50)),
                ('telah_vaksin_dosis_1', models.IntegerField()),
                ('telah_vaksin_dosis_2', models.IntegerField()),
                ('target_vaksin', models.IntegerField()),
                ('per_tanggal', models.DateField()),
            ],
        ),
    ]
