# Generated by Django 3.2.8 on 2021-10-26 12:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Wilayah',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='RumahSakit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=254)),
                ('alamat', models.CharField(max_length=254)),
                ('telp', models.IntegerField()),
                ('mail', models.EmailField(max_length=254)),
                ('wilayah', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daftarRS', to='rujukan.wilayah')),
            ],
        ),
    ]
