# Generated by Django 3.2.8 on 2021-10-28 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rujukan', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rumahsakit',
            options={'ordering': ['nama']},
        ),
        migrations.AlterModelOptions(
            name='wilayah',
            options={'ordering': ['nama']},
        ),
        migrations.AddField(
            model_name='wilayah',
            name='wid',
            field=models.CharField(default='null', max_length=10),
        ),
        migrations.AlterField(
            model_name='rumahsakit',
            name='telp',
            field=models.CharField(max_length=254),
        ),
    ]
