# Generated by Django 3.2.8 on 2021-11-03 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diskusi', '0003_alter_discussion_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='discussion',
            name='user',
            field=models.CharField(default='anonymous', max_length=30),
        ),
    ]
