# Generated by Django 3.2.8 on 2021-11-04 04:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('diskusi', '0004_discussion_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discussion',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
