# Generated by Django 3.2.8 on 2021-10-29 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kewaspadaan', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Waspada',
        ),
    ]
