# Generated by Django 3.2.7 on 2021-11-05 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kewaspadaan', '0003_indikator'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='indikator',
            name='indikator',
        ),
        migrations.AddField(
            model_name='indikator',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='indikator',
            name='source',
            field=models.CharField(max_length=254, null=True),
        ),
    ]
